spring:
  application:
    name: cat
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lidingkui
    url: jdbc:mysql://127.0.0.1:3306/mp?serverTimezone=GMT%2B8&amp&useSSL=false
  jpa:
    show-sql: true  #该配置是为了方便在控制台打印出sql语句   方便调试

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 6666

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.charles.plus.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
